// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**************************************************************************************************
 * This is code encodes the input datasets to the same format that RTScan uses for its experiments.
 *
 **************************************************************************************************/
#include <iostream>
#include <fstream>
#include <vector>
#include <algorithm>
#include <map>
#include <unordered_map>
#include <thread>


std::vector<int32_t> sortData(const std::vector<uint32_t> vals) {
    std::vector<int32_t> ids(vals.size());
    for (int32_t i = 0; i < vals.size(); i++) {
        ids[i] = i;
    }
    std::sort(ids.begin(), ids.end(), [&vals](int32_t x, int32_t y) {
        return vals[x] < vals[y];
    });
    return ids;
}

std::vector<std::map<uint32_t, uint32_t>> encode(std::vector<std::vector<uint32_t>> &data) {
    int32_t ncols = (int32_t) data.size();
    std::vector<std::map<uint32_t, uint32_t>> rowMap(ncols);
    uint32_t npoints = (uint32_t) data[0].size();
    // encode each column
    for (int c = 0; c < ncols; c++) {
        std::cerr << "processing column " << c << std::endl;

        std::vector<uint32_t> colData = data[c];
        std::cerr << "sorting data" << std::endl;
        std::vector<int32_t> pos = sortData(colData);

        std::cerr << "generating counts for mapping" << std::endl;
        std::map<uint32_t,uint32_t> counts;
        for(uint32_t i = 0;i < npoints;i ++) {
            counts[colData[i]] ++;
        }
        std::cerr << "# unique values: " << counts.size() << std::endl;

        std::cerr << "mapping new positions..."  << std::endl;
        uint32_t st = 0;
        for (auto ct: counts) {
            rowMap[c][ct.first] = st;
            st += ct.second;
        }

        std::cerr << "assigning new positions..."  << std::endl;
        for(uint32_t i = 0;i < npoints;i ++) {
            data[c][pos[i]] = i;
        }
    }
    return rowMap;
}

void encodeDataset(std::string fileName, int ncols, uint32_t npoints, std::string opPrefix) {
    std::ifstream binfile(fileName, std::ios::binary|std::ios::ate);
    if(binfile.fail()) {
        std::cerr << "input file does not exist: " << fileName << "\n";
        exit(0);
    }
    size_t sizeInBytes = binfile.tellg();
    binfile.close();

    std::cerr << "input file size: " << sizeInBytes << "\n";
    size_t npts = sizeInBytes / (ncols * sizeof(uint32_t));
    if(npts != npoints) {
        std::cerr << "Error! mismatch in sizes\n";
        exit(0);
    }
    std::vector<std::vector<uint32_t>> opoints(ncols);
    binfile.open(fileName, std::ios::binary);

    for(int c = 0;c < ncols;c ++) {
        opoints[c].resize(npoints);
        binfile.read((char*)opoints[c].data(), npoints * sizeof(uint32_t));
        if(!binfile) {
            std::cerr << "ERROR: all data not read from file:" << fileName << " - " << binfile.gcount() << "," << sizeInBytes << "\n";
            binfile.close();
            exit(0);
        }
    }
    binfile.close();

    std::vector<std::map<uint32_t, uint32_t>> rowMap = encode(opoints);

    std::vector<uint32_t> points;
    for(int c = 0;c < ncols;c ++) {
        points.insert(points.end(), opoints[c].begin(), opoints[c].end());
        std::cerr << "column size: " << c << "," << opoints[c].size() << "\n";
    }
    std::cerr << "points size: " << points.size() << "\n";
    {
        std::cerr << "writing encoded data \n";
        std::string encodedFile = opPrefix + "-data.bin";
        FILE *op = fopen(encodedFile.c_str(),"wb");
        fwrite(points.data(),sizeof(uint32_t),points.size(),op);
        fclose(op);
    }
    {
        std::cerr << "writing encoded map \n";
        std::string encodedFile = opPrefix + "-map.bin";
        FILE *op = fopen(encodedFile.c_str(),"wb");
        int32_t ncols = (int32_t) rowMap.size();
        fwrite(&ncols,sizeof(int32_t),1,op);
        std::cerr << "encoded map size: ";
        for(int32_t c = 0;c < ncols;c ++) {
            uint32_t mapsize = (uint32_t) rowMap[c].size();
            fwrite(&mapsize,sizeof(uint32_t),1,op);
            std::cerr << mapsize << ",";
            for(auto enc: rowMap[c]) {
                fwrite(&enc, sizeof(std::pair<uint32_t, uint32_t>),1,op);
            }
        }
        std::cerr << "\n";
        fclose(op);
    }
}

void encodeAllDatasets() {
    // This folder contains data files that were generated by running
    // https://github.com/AntaresAlice/RTScan/blob/main/script/gen_data.sh
    std::string folder = "/home/akashmaji/Documents/RasterDB/raster-scan/data/";

    // output folder where you want the encoded data
    std::string opfolder = "/home/akashmaji/Documents/RasterDB/raster-scan/encodedData/";

    int32_t dim = 3;
    uint32_t npoints = uint32_t(1e8);
    // the different datasets used for the experiments in the paper
    std::vector<std::string> datasets = {
        "normal_data_1e8_3",
        "zipf1.5_data_1e8_3",
        "zipf1.3_data_1e8_3",
        "zipf1.1_data_1e8_3",
        "uniform_data_1e8_3",
    };
    for(int i = 0;i < datasets.size();i ++) {
        std::cerr << "encoding " << folder + datasets[i] + ".dat" << "\n";
        encodeDataset(folder + datasets[i] + ".dat",dim,npoints,opfolder + datasets[i]);
    }
}

int main() {
    encodeAllDatasets();
    return 0;
}
